accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import signup


urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

projects/urls.py
from django.urls import path
from .views import ProjectListView, ProjectDetailView, ProjectCreateView

urlpatterns = [
    path("", ProjectListView.as_view(), name="list_projects"),
    path("<int:pk>/", ProjectDetailView.as_view(), name="show_project"),
    path("create/", ProjectCreateView.as_view(), name="create_project"),
]

tasks/urls.py
from .views import TaskCreateView, TaskListView, TaskUpdateView
from django.urls import path

urlpatterns = [
    path("create/", TaskCreateView.as_view(), name="create_task"),
    path("mine/", TaskListView.as_view(), name="show_my_tasks"),
    path("<int:pk>/complete/", TaskUpdateView.as_view(), name="complete_task"),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

# from projects import views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("projects/", include("projects.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("list_projects")),
        name="home",
    ),
    path("accounts/", include("accounts.urls")),
    path("tasks/", include("tasks.urls")),
]

projects/models.py
from django.db import models


# Create your models here.
class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    members = models.ManyToManyField("auth.user", related_name="projects")

    def __str__(self):
        return self.name

tasks/models.py
from django.db import models

# Create your models here.
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL


class Task(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    due_date = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(
        "projects.Project", related_name="tasks", on_delete=models.CASCADE
    )
    assignee = models.ForeignKey(
        USER_MODEL, related_name="tasks", on_delete=models.SET_NULL, null=True
    )

    def __str__(self):
        return self.name

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password")
            user = User.objects.create_user(
                username=username, password=password
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()

    context = {"form": form}
    return render(request, "registration/signup.html", context)

projects/views.py
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from .models import Project
from django.contrib.auth.mixins import LoginRequiredMixin


# CHANGE TO CLASS BASED VIEW TOO COMPLICATED
class ProjectListView(LoginRequiredMixin, ListView):
    model = Project
    template_name = "main.html"
    context_object_name = "list_projects"

    def get_queryset(self):
        user = self.request.user
        return Project.objects.filter(members=user)


class ProjectDetailView(LoginRequiredMixin, DetailView):
    model = Project
    template_name = "detail.html"
    fields = "Name", "Assignee", "Start Date", "Due Date", "Is Completed"


class ProjectCreateView(LoginRequiredMixin, CreateView):
    model = Project
    template_name = "create.html"
    fields = "name", "description", "members"

    def get_success_url(self):
        return reverse_lazy("show_project", args=[self.object.id])

tasks/views.py
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Task
from django.urls import reverse_lazy


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    template_name = "create.html"
    fields = "name", "start_date", "due_date", "project", "assignee"

    def get_success_url(self):
        return reverse_lazy("show_project", args=[self.object.project.id])


class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = "mine.html"

    def get_queryset(self):
        return Task.objects.filter(assignee=self.request.user)


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    fields = ("is_completed",)
    success_url = reverse_lazy("show_my_tasks")

projects/templates/create.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Create</title>
    </head>
    <body>
        <header><nav><ul>
            {% if user.is_authenticated %}
                <li> <a href="{% url "show_my_tasks" %}">My Tasks</a></li>
                <li><a href="{% url "list_projects" %}">My Projectss</a></li>
                <li><a href="{% url "logout" %}">Logout</a></li>
            {% else %}
                <li><a href="{% url "login" %}">Login</a></li>
                <li><a href="{% url "signup" %}">Signup</a></li>
            {% endif %}
        </ul></nav></header>
        <main>
            <div>
                <h1>Create a new Project</h1>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button>Create</button>
                </div>
            </main>
        </body>
    </html>

projects/templates/detail.html
<!DOCTYPE html>
<html lang="en">
    {% load markdownify %}

    <head>
        <title>Detail</title>
    </head>
    <body>
        <header><nav><ul>
            {% if user.is_authenticated %}
                <li> <a href="{% url "show_my_tasks" %}">My Tasks</a></li>
                <li><a href="{% url "list_projects" %}">My Projectss</a></li>
                <li><a href="{% url "logout" %}">Logout</a></li>
            {% else %}
                <li><a href="{% url "login" %}">Login</a></li>
                <li><a href="{% url "signup" %}">Signup</a></li>
            {% endif %}
        </ul></nav></header>
        <main>
            <div>
                <h1>{{ project.name }}</h1>
                {{ project.description|markdownify }}
                <h2>Tasks</h2>
                <a href="{% url 'create_task' %}">Create a new task</a>
                {% if project.tasks.all %}
                    <table>
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Assignee</th>
                                <th>Start date</th>
                                <th>Due date</th>
                                <th>Is completed</th>
                            </tr>
                        </thead>
                        {% for task in project.tasks.all %}
                            <tr>
                                <td>{{ task.name }}</td>
                                <td>{{ task.assignee }}</td>
                                <td>{{ task.start_date }}</td>
                                <td>{{ task.due_date }}</td>
                                <td>{{ task.is_completed }}</td>
                            </tr>
                        {% endfor %}
                    </table>
                {% else %}
                    <p>This project has no tasks.</p>
                {% endif %}
            </div>
        </main>
    </body>
</html>

projects/templates/main.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
    </head>
    <body>
        <header><nav><ul>
            {% if user.is_authenticated %}
                <li> <a href="{% url "show_my_tasks" %}">My Tasks</a></li>
                <li><a href="{% url "list_projects" %}">My Projectss</a></li>
                <li><a href="{% url "logout" %}">Logout</a></li>
            {% else %}
                <li><a href="{% url "login" %}">Login</a></li>
                <li><a href="{% url "signup" %}">Signup</a></li>
            {% endif %}
        </ul></nav></header>
        <main>
            <div>
                <h1>My Projects</h1>
                <a href="{% url "create_project" %}">Create a new project</a>
                {% if list_projects|length == 0 %}
                    <p>You are not assigned to any projects</p>
                {% else %}
                    <table>
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Number of tasks</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for project in list_projects %}
                                <tr>
                                    <td>
                                        <a href="{% url 'show_project' project.id %}">
                                            {{ project.name }}
                                        </a>
                                    </td>
                                    <td>{{ project.tasks.all|length}}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                {% endif %}
            </div>
        </main>
    </body>
</html>

tasks/templates/create.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title></title>
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li> <a href="{% url "show_my_tasks" %}">My Tasks</a></li>
                        <li><a href="{% url "list_projects" %}">My Projectss</a></li>
                        <li><a href="{% url "logout" %}">Logout</a></li>
                    {% else %}
                        <li><a href="{% url "login" %}">Login</a></li>
                        <li><a href="{% url "signup" %}">Signup</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <main>
            <div>
                <h1>Create a new task</h1>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button> create</button>
                </div>
            </main>
        </body>
    </html>

tasks/templates/mine.html
<!DOCTYPE html>
<html lang="en">
    <head><title>My Tasks</title></head>
    <body>
        <header><nav><ul>
            {% if user.is_authenticated %}
                <li> <a href="{% url "show_my_tasks" %}">My Tasks</a></li>
                <li><a href="{% url "list_projects" %}">My Projectss</a></li>
                <li><a href="{% url "logout" %}">Logout</a></li>
            {% else %}
                <li><a href="{% url "login" %}">Login</a></li>
                <li><a href="{% url "signup" %}">Signup</a></li>
            {% endif %}
        </ul></nav></header>
        <main>
            <div>
                <h1>My Tasks</h1>
                {% if task_list|length > 0 %}
                    <table>
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Start date</th>
                                <th>End date</th>
                                <th>Is complete</th>
                            </tr>
                        </thead>
                {% endif %}
                <tbody>
                    {% if task_list|length == 0 %}
                        <p>You have no tasks</p>
                    {% endif %}
                    {% for task in task_list %}
                        <tr>
                            <td>{{ task.name }}</td>
                            <td>{{ task.start_date }}</td>
                            <td>{{ task.due_date }}</td>
                            <td>{% if task.is_completed %}</td>
                                <p>Done</p>
                            {% else %}
                                <form method="post" action="{% url 'complete_task' task.id %}">
                                    {% csrf_token %}
                                    <input type="hidden" name="is_completed" value="True">
                                    <button>Complete</button>
                                </form>
                            {% endif %}
                            </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </main>
</html>